name: Fetch Firefox default preferenecs

on:
  push:
    tags: "*.*.*"

jobs:
  fetch:
    strategy:
      matrix:
        firefox: ["132.0","132.0.1","131.0","131.0.2","131.0.3","130.0","130.0.1","129.0","129.0.1","129.0.2","128.0","128.0.2","128.0.3","128.1.0","128.2.0","128.3.0","128.3.1","128.4.0","127.0","127.0.1","127.0.2","126.0","126.0.1","125.0.1","125.0.2","125.0.3","124.0","124.0.1","124.0.2","123.0","123.0.1","122.0","122.0.1","121.0","121.0.1","120.0","120.0.1","119.0","119.0.1","118.0","118.0.1","118.0.2","117.0","117.0.1","116.0","116.0.1","116.0.2","116.0.3","115.0","115.0.1","115.0.2","115.0.3","115.1.0","115.2.0","115.2.1","115.3.0","115.3.1","115.4.0","115.5.0","115.6.0","115.7.0","115.8.0","115.9.0","115.9.1","115.10.0","115.11.0","115.12.0","115.13.0","115.14.0","115.15.0","115.16.0","115.16.1","115.17.0","114.0","114.0.1","114.0.2","113.0","113.0.1","113.0.2","112.0","112.0.1","112.0.2","111.0","111.0.1","110.0"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout firefox-default-prefs-fetcher
        uses: actions/checkout@v4

      - name: Setup Firefox version ${{ matrix.firefox }}
        uses: browser-actions/setup-firefox@v1
        with: 
          firefox-version: ${{ matrix.firefox }}
      
      - name: Setup PDM/Python
        uses: pdm-project/setup-pdm@v4

      - name: Install Python dependencies
        run: pdm install
      
      - name: Run firefox-defaults-prefs-fetcher
        run: pdm run start --ci
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-firefox-${{ matrix.firefox }}
          path: out/*


  release:
    needs: fetch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - run: ls -R
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: "*/*.json"
